#!/usr/bin/env bash
#this prints Holberton School 10 times, except the 9th time will pring Hi 

i=0
while [ $i -lt 10 ];
do 
	echo Holberton School
	(( i++ ))
	if (( i == 9))	
	then
	echo Hi
	fi
done
