#!/usr/bin/env bash
#This script outputs Best School, badluck 4th, goodluck 8th.
i=0
 while [ "$i" -le 10 ]
 do  if (($i == 3))
     then  echo "bad luck"
      elif  (($i == 7))
      then  echo "good luck"
      else  echo "Best School"
     fi    
     ((i++)) 
done
