#!/usr/bin/env bash
#This script outputs 1 to 10 "Best School". "badluck" 4th and "goodluck" 8th.
i=0
 while [ "$i" -le 9 ]
 do  if ((i == 3))
     then  echo "bad luck"
      elif  ((i == 7))
      then  echo "good luck"
      else  echo "Best School"
     fi    
     ((i++)) 
done
