#!/usr/bin/env bash
#While loop that displays the time 12 hours and 59 minutes,0 to 12, 1 to 59.

i=0
k=1
while [ "$i" -le 12 ]
do
    echo "Hour: $i"
    while [ $k -le 59 ]
    do
	echo "$k"
	k=$((k + 1))
    done
    k=1
   i=$((i + 1))
done
