#!/usr/bin/env bash
# Script that displays the time  first 12 hours and 59 minutes

i=0
k=1
while [ "$i" -le 12 ]
do
    echo "Hour: $i"
    while [ $k -le 59 ]
    do
	echo "$k"
	k=$((k + 1))
    done
    k=1
   i=$((i + 1))
done
